### ISSUE TITLE
Not compatible with Go Modules 1.10+: needs go.mod and semver git tag

### ISSUE THREAD

**Issue by coolaj86** [namedotcom/go#3]
This has really weird version info:

<https://pkg.go.dev/github.com/namedotcom/go@v0.0.0-20180403034216-08470befbe04/namecom?tab=doc>

**Comment by coolaj86** [comment]
Steps to Add:

```bash
go mod init github.com/namedotcom/go
go mod tidy
git add go.mod go.sum
git commit -m "v4.0.0"
git tag v4.0.0
git push
git push --tags
```

**Comment by mingcheng** [comment]
https://github.com/namedotcom/go/pull/5

**Comment by patramsey** [comment]
This was addressed with https://github.com/namedotcom/go/pull/4
